name: Deploy to GitHub Pages

on:
  push:
    branches: [main]  # Correct syntax for branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3  # Correct action name
        with:
          publish_dir: "./Gear Hub"  # Add quotes for folders with spaces
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Fixed token syntax